# Generated by Django 3.2.5 on 2022-04-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z_hot',
            fields=[
                ('Z_hot_list_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='知乎热榜id')),
                ('Z_hot_list_time', models.DateTimeField(auto_now_add=True, verbose_name='知乎热榜更新时间')),
                ('Z_hot_list_sum', models.IntegerField(default=0, verbose_name='知乎热榜查看次数')),
            ],
        ),
    ]
