# Generated by Django 3.2.5 on 2022-04-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_z_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z_hot_item',
            fields=[
                ('Z_hot_item_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='知乎热榜条目id')),
                ('Z_item_rank', models.IntegerField(verbose_name='知乎热榜条目排名')),
                ('Z_item_name', models.CharField(max_length=500, verbose_name='知乎热榜条目标题')),
                ('Z_item_hot', models.CharField(max_length=500, verbose_name='知乎热榜条目热度值')),
                ('Z_item_cover_url', models.CharField(max_length=500, verbose_name='知乎热榜条目封面图片url')),
                ('Z_item_click_sum', models.IntegerField(default=0, verbose_name='知乎热榜条目查看次数')),
                ('Z_item_url', models.CharField(max_length=500, verbose_name='知乎热榜条目url')),
                ('Z_hot_list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='z_hot', to='api.z_hot', verbose_name='知乎热榜id')),
            ],
        ),
    ]
