# Generated by Django 3.2.5 on 2022-04-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_z_hot_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='z_hot_item',
            name='Z_hot_list_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.z_hot', verbose_name='知乎热榜id'),
        ),
    ]
