# Generated by Django 3.2.5 on 2022-04-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_z_hot_item_z_hot_list_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='z_hot_item',
            old_name='Z_hot_item_id',
            new_name='Z_item_id',
        ),
    ]
