# Generated by Django 3.2.5 on 2022-04-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_z_hot_item_id_z_hot_item_z_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='z_hot_item',
            name='Z_hot_list_id',
        ),
        migrations.DeleteModel(
            name='Z_hot',
        ),
        migrations.DeleteModel(
            name='Z_hot_item',
        ),
    ]
