# Generated by Django 3.2.5 on 2022-06-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220410_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='crawlTimeManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biliHotTime', models.IntegerField(default=1, verbose_name='b站热门刷新时间/min')),
                ('weiboHotTime', models.IntegerField(default=1, verbose_name='微博热门刷新时间/min')),
                ('zhihuHotTime', models.IntegerField(default=1, verbose_name='知乎热门刷新时间/min')),
                ('biliDynasicTime', models.IntegerField(default=1, verbose_name='b站动态刷新时间/min')),
                ('weiboDynasicTime', models.IntegerField(default=1, verbose_name='微博动态刷新时间/min')),
            ],
        ),
    ]
