# Generated by Django 3.2.5 on 2022-04-29 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bili_hot',
            fields=[
                ('Bili_hot_list_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='b站热门id')),
                ('Bili_hot_list_time', models.DateTimeField(auto_now_add=True, verbose_name='b站热门更新时间')),
                ('Bili_hot_list_sum', models.IntegerField(default=0, verbose_name='b站热门查看次数')),
            ],
        ),
        migrations.CreateModel(
            name='up_list',
            fields=[
                ('Bili_up_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='b站up主id')),
                ('Bili_up_name', models.CharField(max_length=500, verbose_name='b站up主昵称')),
                ('Bili_up_face_url', models.CharField(max_length=500, verbose_name='b站up主头像url')),
            ],
        ),
        migrations.CreateModel(
            name='follow_list',
            fields=[
                ('Bili_follow_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='关注列表关系id')),
                ('Bili_is_special', models.IntegerField(default=0, verbose_name='是否特别关注')),
                ('Bili_up_id', models.ForeignKey(db_column='Bili_up_id', on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_list', to='bili.up_list', verbose_name='b站up主id')),
                ('Bili_user_id', models.ForeignKey(db_column='Bili_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='follow_auth_user', to=settings.AUTH_USER_MODEL, verbose_name='本站用户id')),
            ],
        ),
        migrations.CreateModel(
            name='dynasic',
            fields=[
                ('Bili_dynasic_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='b站动态id')),
                ('Bili_type', models.IntegerField(verbose_name='b站动态类型')),
                ('Bili_share', models.IntegerField(verbose_name='b站动态分享数')),
                ('Bili_comment', models.IntegerField(verbose_name='b站动态评论数')),
                ('Bili_like', models.IntegerField(verbose_name='b站动态点赞数')),
                ('Bili_post_time', models.IntegerField(verbose_name='b站动态发布时间')),
                ('Bili_url_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='b站动态链接id')),
                ('Bili_content', models.CharField(blank=True, max_length=5000, null=True, verbose_name='b站动态文字内容')),
                ('Bili_pic_urls', models.CharField(blank=True, max_length=900, null=True, verbose_name='b站动态图片链接集合')),
                ('Bili_video_title', models.CharField(blank=True, max_length=500, null=True, verbose_name='b站动态视频标题')),
                ('Bili_video_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='b站动态视频url')),
                ('Bili_video_pic_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='b站动态视频封面url')),
                ('Bili_video_desc', models.CharField(blank=True, max_length=1000, null=True, verbose_name='b站动态视频简介')),
                ('Bili_original_up', models.CharField(blank=True, max_length=1000, null=True, verbose_name='b站动态转发的原up')),
                ('Bili_original_content', models.CharField(blank=True, max_length=5000, null=True, verbose_name='b站动态转发的原内容')),
                ('Bili_up_id', models.ForeignKey(db_column='Bili_up_id', on_delete=django.db.models.deletion.CASCADE, related_name='Bili_up_list', to='bili.up_list', verbose_name='b站up主id')),
            ],
        ),
        migrations.CreateModel(
            name='Bili_hot_item',
            fields=[
                ('Bili_item_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='b站热门视频id')),
                ('Bili_item_name', models.CharField(max_length=500, verbose_name='b站热门视频标题')),
                ('Bili_item_up', models.CharField(max_length=500, verbose_name='b站热门视频Up主')),
                ('Bili_item_view', models.IntegerField(default=0, verbose_name='b站热门视频观看数')),
                ('Bili_item_comment', models.IntegerField(default=0, verbose_name='b站热门视频评论数')),
                ('Bili_item_cover_url', models.CharField(max_length=500, verbose_name='b站热门视频封面图片url')),
                ('Bili_item_click_sum', models.IntegerField(default=0, verbose_name='b站热门视频点击次数')),
                ('Bili_item_url', models.CharField(max_length=500, verbose_name='b站热门视频url')),
                ('Bili_hot_list_id', models.ForeignKey(db_column='Bili_hot_list_id', on_delete=django.db.models.deletion.CASCADE, related_name='bili_hot', to='bili.bili_hot', verbose_name='b站热门id')),
            ],
        ),
    ]
