# Generated by Django 3.2.5 on 2022-04-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bili', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dynasic_list',
            fields=[
                ('up_date_time', models.DateTimeField(db_index=True, primary_key=True, serialize=False, verbose_name='b站动态更新时间')),
            ],
        ),
    ]
