# Generated by Django 3.2.5 on 2022-04-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bili', '0002_dynasic_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dynasic_list',
            new_name='dynasic_time_list',
        ),
    ]
