# Generated by Django 3.2.5 on 2022-04-10 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weibo_hot',
            fields=[
                ('Weibo_hot_list_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='微博热门id')),
                ('Weibo_hot_list_time', models.DateTimeField(auto_now_add=True, verbose_name='微博热门更新时间')),
                ('Weibo_hot_list_sum', models.IntegerField(default=0, verbose_name='微博热门查看次数')),
            ],
        ),
        migrations.CreateModel(
            name='Weibo_hot_item',
            fields=[
                ('Weibo_item_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='微博热门条目id')),
                ('Weibo_item_rank', models.IntegerField(verbose_name='微博热门条目排名')),
                ('Weibo_item_name', models.CharField(max_length=500, verbose_name='微博热门条目标题')),
                ('Weibo_item_tag', models.CharField(max_length=500, verbose_name='微博热门条目tag')),
                ('Weibo_item_hot', models.CharField(max_length=500, verbose_name='微博热门条目热度值')),
                ('Weibo_item_cover_url', models.CharField(max_length=500, verbose_name='微博热门条目封面图片url')),
                ('Weibo_item_click_sum', models.IntegerField(default=0, verbose_name='微博热门条目点击次数')),
                ('Weibo_item_url', models.CharField(max_length=500, verbose_name='微博热门条目url')),
                ('Weibo_hot_list_id', models.ForeignKey(db_column='Weibo_hot_list_id', on_delete=django.db.models.deletion.CASCADE, related_name='weibo_hot', to='weibo.weibo_hot', verbose_name='微博热门id')),
            ],
        ),
    ]
