# Generated by Django 3.2.5 on 2022-04-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibo_hot_item',
            name='Weibo_item_cover_url',
        ),
        migrations.RemoveField(
            model_name='weibo_hot_item',
            name='Weibo_item_tag',
        ),
    ]
