# Generated by Django 3.2.5 on 2022-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0002_auto_20220428_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weibo_hot_item',
            name='Weibo_item_hot',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='微博热门条目热度值'),
        ),
    ]
