# Generated by Django 3.2.5 on 2022-05-01 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weibo', '0003_alter_weibo_hot_item_weibo_item_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='dynasic_time_list',
            fields=[
                ('up_date_time', models.DateTimeField(db_index=True, primary_key=True, serialize=False, verbose_name='微博动态更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='up_list',
            fields=[
                ('Weibo_up_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='微博博主id')),
                ('Weibo_up_name', models.CharField(max_length=500, verbose_name='微博博主昵称')),
                ('Weibo_up_face_url', models.CharField(max_length=500, verbose_name='微博博主头像url')),
            ],
        ),
        migrations.CreateModel(
            name='follow_list',
            fields=[
                ('Weibo_follow_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='关注列表关系id')),
                ('Weibo_is_special', models.IntegerField(default=0, verbose_name='是否特别关注')),
                ('Weibo_up_id', models.ForeignKey(db_column='Weibo_up_id', on_delete=django.db.models.deletion.CASCADE, related_name='wbfollow_up_list', to='weibo.up_list', verbose_name='微博博主id')),
                ('Weibo_user_id', models.ForeignKey(db_column='Weibo_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='wbfollow_auth_user', to=settings.AUTH_USER_MODEL, verbose_name='本站用户id')),
            ],
        ),
        migrations.CreateModel(
            name='dynasic',
            fields=[
                ('Weibo_dynasic_id', models.AutoField(db_index=True, primary_key=True, serialize=False, verbose_name='微博动态id')),
                ('Weibo_share', models.IntegerField(verbose_name='微博动态分享数')),
                ('Weibo_comment', models.IntegerField(verbose_name='微博动态评论数')),
                ('Weibo_like', models.IntegerField(verbose_name='微博动态点赞数')),
                ('Weibo_post_time', models.IntegerField(verbose_name='微博动态发布时间')),
                ('Weibo_url_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='微博动态链接id')),
                ('Weibo_content', models.CharField(blank=True, max_length=5000, null=True, verbose_name='微博动态文字内容')),
                ('Weibo_pic_urls', models.CharField(blank=True, max_length=900, null=True, verbose_name='微博动态图片链接集合')),
                ('Weibo_up_id', models.ForeignKey(db_column='Weibo_up_id', on_delete=django.db.models.deletion.CASCADE, related_name='Weibo_up_list', to='weibo.up_list', verbose_name='微博博主id')),
            ],
        ),
    ]
