# Generated by Django 3.2.5 on 2022-05-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0004_dynasic_dynasic_time_list_follow_list_up_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='up_list',
            name='Weibo_up_id',
            field=models.CharField(db_index=True, max_length=500, primary_key=True, serialize=False, verbose_name='微博博主id'),
        ),
    ]
