# Generated by Django 3.2.5 on 2022-05-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0005_alter_up_list_weibo_up_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynasic',
            name='Weibo_post_time',
            field=models.CharField(max_length=500, verbose_name='微博动态发布时间'),
        ),
    ]
