# Generated by Django 3.2.5 on 2022-05-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0006_alter_dynasic_weibo_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynasic',
            name='Weibo_post_time',
            field=models.IntegerField(verbose_name='微博动态发布时间'),
        ),
    ]
